FROM apache/airflow:2.10.4-python3.9

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    scikit-learn==1.6.1 lightgbm==4.6.0 pyarrow
